In [17]:
import pandas as pd

In [18]:
df_raw = pd.read_csv('scrapper/output/glassdoor_jobs.csv')

df_raw.head()

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,0,Data Scientist,$53K-$91K (Glassdoor est.),"Data Scientist\nLocation: Albuquerque, NM\nEdu...",3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 to 1000 employees,1973,Company - Private,Aerospace & Defense,Aerospace & Defense,$50 to $100 million (USD),-1
1,1,Healthcare Data Scientist,$63K-$112K (Glassdoor est.),What You Will Do:\n\nI. General Summary\n\nThe...,3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+ employees,1984,Other Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1
2,2,Data Scientist,$80K-$90K (Glassdoor est.),"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,Company - Private,Security Services,Business Services,$100 to $500 million (USD),-1
3,3,Data Scientist,$56K-$97K (Glassdoor est.),*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa..."
4,4,Data Scientist,$86K-$143K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee"

In [19]:
df_raw.count()

Unnamed: 0           956
Job Title            956
Salary Estimate      956
Job Description      956
Rating               956
Company Name         956
Location             956
Headquarters         956
Size                 956
Founded              956
Type of ownership    956
Industry             956
Sector               956
Revenue              956
Competitors          956
dtype: int64

In [31]:
df = df_raw.copy(deep=True)

In [32]:
df.head()

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,0,Data Scientist,$53K-$91K (Glassdoor est.),"Data Scientist\nLocation: Albuquerque, NM\nEdu...",3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 to 1000 employees,1973,Company - Private,Aerospace & Defense,Aerospace & Defense,$50 to $100 million (USD),-1
1,1,Healthcare Data Scientist,$63K-$112K (Glassdoor est.),What You Will Do:\n\nI. General Summary\n\nThe...,3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+ employees,1984,Other Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1
2,2,Data Scientist,$80K-$90K (Glassdoor est.),"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,Company - Private,Security Services,Business Services,$100 to $500 million (USD),-1
3,3,Data Scientist,$56K-$97K (Glassdoor est.),*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa..."
4,4,Data Scientist,$86K-$143K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee"

## salary parsing
## company name, text only
## state field
## age of company
## parsing of JD (python, skills etc)

### 1. salary parsing

In [33]:
df = df[df['Salary Estimate'] != '-1']

In [34]:
df.count()

Unnamed: 0           742
Job Title            742
Salary Estimate      742
Job Description      742
Rating               742
Company Name         742
Location             742
Headquarters         742
Size                 742
Founded              742
Type of ownership    742
Industry             742
Sector               742
Revenue              742
Competitors          742
dtype: int64

In [35]:
salary = df['Salary Estimate'].apply(lambda x : x.split('(')[0])

salary.head()

0     $53K-$91K
1    $63K-$112K
2     $80K-$90K
3     $56K-$97K
4    $86K-$143K
Name: Salary Estimate, dtype: object

In [36]:
minus_kd = salary.apply(lambda x : x.replace('K', '').replace('$', '').replace('L', ''))

In [37]:
minus_kd

0       53-91
1      63-112
2       80-90
3       56-97
4      86-143
        ...
950    58-111
951    72-133
952     56-91
953    95-160
955    61-126
Name: Salary Estimate, Length: 742, dtype: object

In [38]:
df['hourly'] = df['Salary Estimate'].apply(lambda x : 1 if 'per hour' in x.lower() else 0)

df['hourly']

0      0
1      0
2      0
3      0
4      0
      ..
950    0
951    0
952    0
953    0
955    0
Name: hourly, Length: 742, dtype: int64

In [39]:
df['employer_provided'] = df['Salary Estimate'].apply(lambda x : 1 if 'employer provided salary:' in x.lower() else 0)

df['employer_provided']

0      0
1      0
2      0
3      0
4      0
      ..
950    0
951    0
952    0
953    0
955    0
Name: employer_provided, Length: 742, dtype: int64

In [40]:
min_hr = minus_kd.apply(lambda x : x.lower().replace('per hour', '').replace('employer provided salary:', ''))

In [41]:
min_hr

0       53-91
1      63-112
2       80-90
3       56-97
4      86-143
        ...
950    58-111
951    72-133
952     56-91
953    95-160
955    61-126
Name: Salary Estimate, Length: 742, dtype: object

In [42]:
df['min_salary'] = min_hr.apply(lambda x : int(x.split('-')[0]))

df['max_salary'] = min_hr.apply(lambda x : int(x.split('-')[1]))

df['avg_salary'] = (df.min_salary + df.max_salary) / 2

df.head()

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,hourly,employer_provided,min_salary,max_salary,avg_salary
0,0,Data Scientist,$53K-$91K (Glassdoor est.),"Data Scientist\nLocation: Albuquerque, NM\nEdu...",3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 to 1000 employees,1973,Company - Private,Aerospace & Defense,Aerospace & Defense,$50 to $100 million (USD),-1,0,0,53,91,72.0
1,1,Healthcare Data Scientist,$63K-$112K (Glassdoor est.),What You Will Do:\n\nI. General Summary\n\nThe...,3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+ employees,1984,Other Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,0,0,63,112,87.5
2,2,Data Scientist,$80K-$90K (Glassdoor est.),"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,Company - Private,Security Services,Business Services,$100 to $500 million (USD),-1,0,0,80,90,85.0
3,3,Data Scientist,$56K-$97K (Glassdoor est.),*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa...",0,0,56,97,76.5
4,4,Data Scientist,$86K-$143K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",0,0,86,143,114.5

### 2. Company name - text only

In [44]:
df['company_txt'] = df.apply(lambda x : x['Company Name'] if x['Rating'] < 0 else x['Company Name'][:-3], axis=1)

df['company_txt']

0                          Tecolote Research\n
1      University of Maryland Medical System\n
2                                    KnowBe4\n
3                                       PNNL\n
4                         Affinity Solutions\n
                        ...
950                                      GSK\n
951                               Eventbrite\n
952           Software Engineering Institute\n
953                             Numeric, LLC\n
955             Riverside Research Institute\n
Name: company_txt, Length: 742, dtype: object

### 3. State Field

In [46]:
df['job_state'] = df['Location'].apply(lambda x : x.split(',')[1])

df['job_state'].head()

0     NM
1     MD
2     FL
3     WA
4     NY
Name: job_state, dtype: object

In [47]:
df['job_state']

0       NM
1       MD
2       FL
3       WA
4       NY
      ...
950     MA
951     TN
952     PA
953     PA
955     OH
Name: job_state, Length: 742, dtype: object

In [48]:
df['same_state'] = df.apply(lambda x : 1 if x.Location == x.Headquarters else 0, axis = 1)

In [49]:
df['age'] = df.Founded.apply(lambda x : x if x < 1 else 2026 - x)

In [53]:
df[['age', 'same_state']]

     age  same_state
0     53           0
1     42           0
2     16           1
3     61           1
4     28           1
..   ...         ...
950  196           0
951   20           0
952   42           1
953   -1           0
955   59           0

[742 rows x 2 columns]

### 3. Parsing of JD (finding key terms like Python, R studio)

In [55]:
df['python_yn'] = df['Job Description'].apply(lambda x : 1 if 'python' in x.lower() else 0)

df['R_yn'] = df['Job Description'].apply(lambda x : 1 if 'r studio' in x.lower() or 'r-studio' in x.lower() else 0)

In [56]:
df[['python_yn', 'R_yn']]

     python_yn  R_yn
0            1     0
1            1     0
2            1     0
3            1     0
4            1     0
..         ...   ...
950          0     0
951          1     0
952          0     0
953          0     0
955          1     0

[742 rows x 2 columns]

In [57]:
df['spark'] = df['Job Description'].apply(lambda x : 1 if 'spark' in x.lower() else 0)

In [58]:
df['spark']

0      0
1      0
2      1
3      0
4      0
      ..
950    0
951    1
952    0
953    0
955    0
Name: spark, Length: 742, dtype: int64

In [59]:
df['aws'] = df['Job Description'].apply(lambda x : 1 if 'aws' in x.lower() else 0)

In [60]:
df['excel'] = df['Job Description'].apply(lambda x : 1 if 'excel' in x.lower() else 0)

In [61]:
df.columns

Index(['Unnamed: 0', 'Job Title', 'Salary Estimate', 'Job Description',
       'Rating', 'Company Name', 'Location', 'Headquarters', 'Size', 'Founded',
       'Type of ownership', 'Industry', 'Sector', 'Revenue', 'Competitors',
       'hourly', 'employer_provided', 'min_salary', 'max_salary', 'avg_salary',
       'company_txt', 'job_state', 'same_state', 'age', 'python_yn', 'R-yn',
       'R_yn', 'spark', 'aws', 'excel'],
      dtype='object')

In [65]:
df = df.drop('Unnamed: 0', axis = 1)

In [66]:
df = df.drop('R-yn', axis = 1)

In [68]:
df.to_csv('output/salary_data_cleaned.csv', index = True)